### ISSUE TITLE
The number of method references in a .dex file cannot exceed 64K

### ISSUE THREAD

**Issue by GuiCavi** [wuxudong/react-native-charts-wrapper#85] opened 2017-07-12 18:46 UTC
Hi, on my project we've installed `RNChartsWrapper` and we've ran into a problem: when compiling (react-native run-android), everything goes fine until

    :app:transformClassesWithDexForDebug

where it takes a long time to execute and, when it's done, shows the error on title. 

This is an image from terminal where you can see on left the output WITHOUT `RNChartsWrapper` and on right WITH `RNChartsWrapper`.
![dexproblem](https://user-images.githubusercontent.com/7794819/28133602-f68e254e-6716-11e7-81b1-1fa19f71ea8e.png)

---

I've tried the solution given on [Android Developers](https://developer.android.com/tools/building/multidex.html), enabling MultiDex but nothing worked.

Can this be a issue related with [Need for help section](https://github.com/wuxudong/react-native-charts-wrapper#need-for-help)? I mean, maybe the library is injecting too many methods and triggering the error (I don't believe it's injecting 56k methods, that's problably insane).

One more commet, my partner cloned our repo and tried to run `react-native run-android` and it worked, perfectly, so I updated everything on my PC, but the problem is still there.

---

```js
"dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.44.0",
    "react-native-svg": "5.1.8", //last library installed before RNChartsWrapper, works till here
    "react-native-charts-wrapper": "^0.2.10",
},
"devDependencies": {
    "@kadira/react-native-storybook": "^2.0.0",
    "babel-jest": "19.0.0",
    "babel-preset-react-native": "1.9.1",
    "jest": "19.0.2",
    "react-test-renderer": "15.4.2",
    "webpack-dev-server": "^2.5.0"
},
```

Any answer would be helpful because I ran out of options.
Thanks.

[]'s

**Comment by GuiCavi** [comment] 2017-07-12 18:47
@renanpupin

**Comment by ramki1979** [comment] 2017-07-13 10:56
https://jeroenmols.com/blog/2016/05/06/methodcount/

Go to the above article and see yourself, the culprit.

**Comment by GuiCavi** [comment] 2017-07-13 17:11
Hi, thanks for the response. I tried what you said (following the tutorial) and tested 4 cases:

1- My project with RNCW --> **FAILED**. Don't go over the Dex process
2- My project without RNCW --> **SUCCESS**. (First image)
3- A new project without ANYTHING --> **SUCCESS**. (Second image)
4- A new project with RNCW --> **SUCCESS**. (Third image)

Next you can see the outputs

![dexproblem2](https://user-images.githubusercontent.com/7794819/28177999-356ddd24-67d3-11e7-8a05-861fd1ed34e1.png)

As you can see, RNCW injects 2.852 methods (I don't know if it's only for this or for every project). I know the problem now isn't related with this library, but I need to continue coding and for now on, we have to use RNCW.

My partner tried this method on his cloned project and the result was **64.911 (99.01%)** (IIRC), but he can run his project **_normally_**. I believe if we install more any library it will go over 100% and his project will stop running too.

For now on, I'll comment everything related with RNCW and keep coding my tasks. Still trying to solve this problem. Waiting for some light too.

Thanks.

[]'s

**Comment by wuxudong** [comment] 2017-11-19 08:26
It seems the problem is not related to RNCW, I think it is caused by too many libs are introduced.

Maybe MultiDex can help.

Close the issue. Reopen it if you have any questions.

**Closed by wuxudong** 2017-11-19 08:26 UTC

**Comment by wangshuwen1107** [comment] 2018-03-22 08:17
@GuiCavi  i have same problem in my project how to fix  it

**Comment by GuiCavi** [comment] 2018-03-22 22:24
Hi @wangshuwen1107, I really can't remember how we fixed it. Just can confirm we don't have RNChartsWrapper installed anymore, so I believe we are not using it. Sorry for not helping with the solution.

What I can see here in my package.json is a package called victory-native, I believe someone was able to implement our feature with it. Maybe it can help.

**Comment by ramki1979** [comment] 2018-03-23 08:45
If you gone beyond the limit then simply ass the Multi-dex support.
Check google how to add Multi-dex support to you android project.

**Comment by ramki1979** [comment] 2018-03-23 10:42
> in your app/build.gradle, Add the below lines .  [Extracted from my RN working project]
```
android {
   defaultConfig {
      multiDexEnabled true
   }
   dexOptions {
      jumboMode true
   }
}

dependencies {
   compile 'com.android.support:multidex:1.0.1'
}
```
 
> MainApplication.java 
```
@Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(base);
     MultiDex.install(this);
  }
```
