### ISSUE TITLE
[IOS] Line Chart Exception Invalid type in JSON write (NS__Date)

### ISSUE THREAD

**Issue by thoth-nexlesoft** [wuxudong/react-native-charts-wrapper#98] opened 2017-08-07 07:51 UTC
![simulator screen shot aug 7 2017 2 18 56 pm](https://user-images.githubusercontent.com/25680402/29016214-b4b9a980-7b7b-11e7-9b0c-bc4a75df7dc8.png)

Some time IOS show error "Exception Invalid type in JSON write (NS__Date)".
When I run app on Xcode. I see the error "[error][tid:main][RCTUIManager.m:1203] Error setting property 'data' of RNLineChart with tag #730: Exception thrown while executing UI block: Invalid type in JSON write (__NSDate)" . Can you help me? @wuxudong

**Comment by wuxudong** [comment] 2017-11-19 14:03
What is your data? 
It may be caused by invalid data.

Close this issue. Please reopen it if you have any question.

**Closed by wuxudong** 2017-11-19 14:03 UTC
