### ISSUE TITLE
xAxis valueFormatter can't refresh when Barchart same data  (xAxis value change)

### ISSUE THREAD

**Issue by s349856186** [wuxudong/react-native-charts-wrapper#386] opened 2018-09-04 07:14 UTC
![image](https://user-images.githubusercontent.com/2498958/45015578-c2fe7e80-b054-11e8-8189-e2815a1737fb.png)
![image](https://user-images.githubusercontent.com/2498958/45015631-e4f80100-b054-11e8-8c76-cb677bdece0a.png)

When I get the same Barchart data value = 0, the value of xAxis valueFormatter is different, the value of xAxis valueFormatter will not be refreshed.

**Comment by angelos3lex** [comment] 2018-09-04 08:54
Possible duplicate of #377

**Comment by s349856186** [comment] 2018-09-04 08:58
Looks like yes, have you solved this problem? @angelos3lex

**Closed** 2018-09-27 02:16 UTC

**Comment by wuxudong** [comment] 2018-10-12 10:39
Why do you want to refresh xAxis when data is same?

and please provide code and config to reproduce it, you can use local data and setTimeout to simulate the real situation.

**Comment by s349856186** [comment] 2018-10-13 04:19
@wuxudong My data sometimes is same，but xAxis value different。when data is same，I want to refresh the xAxis value.
![image](https://user-images.githubusercontent.com/2498958/46901169-2f389180-cee1-11e8-83d1-fc17d258f42f.png)
![image](https://user-images.githubusercontent.com/2498958/46901175-424b6180-cee1-11e8-9c82-09c5b55e70bb.png)
![image](https://user-images.githubusercontent.com/2498958/46901182-89d1ed80-cee1-11e8-9171-c7dbc79b5959.png)
![image](https://user-images.githubusercontent.com/2498958/46901212-462bb380-cee2-11e8-8979-38fa8bce48a3.png)

**Comment by wuxudong** [comment] 2018-10-13 05:35
Works fine for me.

LineChartGradientScreen.js

```
constructor() {
    super();

    this.state = {
      xAxis: {
                          enabled: true,
                          granularity: 1,
                          drawLabels: true,
                          position: "BOTTOM",
                          drawAxisLine: true,
                          drawGridLines: false,
                          fontFamily: "HelveticaNeue-Medium",
                          fontWeight: "bold",
                          textSize: 12,
                          textColor: processColor("gray"),
                          valueFormatter: ["M", "T", "W", "T", "F", "S"]
                        }
    };
  }

  componentDidMount() {
      setTimeout(() => {
        this.setState({xAxis: {
                          enabled: true,
                          granularity: 1,
                          drawLabels: true,
                          position: "BOTTOM",
                          drawAxisLine: true,
                          drawGridLines: false,
                          fontFamily: "HelveticaNeue-Medium",
                          fontWeight: "bold",
                          textSize: 12,
                          textColor: processColor("gray"),
                          valueFormatter: ["x", "y", "z", "o", "a", "f"]
                        }}) 
      }, 5000)

  }

```

![out](https://user-images.githubusercontent.com/1391101/46901771-1e414d80-ceec-11e8-91dc-3b0fb890d058.gif)

**Comment by s349856186** [comment] 2018-10-13 08:58
@wuxudong Thank you for your reply, I will check the code again.
